openapi: 3.0.3
info:
  title: Sync API (M2 初版)
  version: "0.1"
  description: |-
    シンプルな Push/Pull 用の API 断片（M2 初版）。
servers:
  - url: http://localhost:8080
paths:
  /sync/pull:
    get:
      summary: Export change_log since lsn
      parameters:
        - in: query
          name: from_lsn
          schema:
            type: integer
            default: 0
          required: false
          description: "クライアントが持つ last_lsn。これより大きい変更を返す。省略時は 0 として全件返す。"
        - in: query
          name: client_id
          schema:
            type: string
          required: false
          description: "要求元クライアント ID（オプション）。"
      responses:
        '200':
          description: JSON Lines stream
          content:
            application/x-ndjson:
              schema:
                type: string
              example: "__meta__ {\"tx_grouping\":true}\n{...}\n{...}\n"
            application/json:
              schema:
                type: string
  /sync/push:
    post:
      summary: Import change_log file (JSON Lines)
      requestBody:
        required: true
        content:
          application/x-ndjson:
            schema:
              type: string
            description: "NDJSON 形式の changelog をそのままリクエストボディに送信します。サーバ側で一時ファイルに保存してインポートします。"
      responses:
        '200':
          description: import result
          content:
            application/json:
              schema:
                type: string
                example: "ok"
          text/plain:
            schema:
              type: string
              example: "ok"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: Token
