name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      use_secrets:
        description: 'Set to "true" to populate repository secrets into the environment for the E2E job'
        required: false
        default: 'false'

env:
  MAVEN_OPTS: -Xmx1024m

jobs:
  build:
    name: Build and unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and run unit tests
        working-directory: app-core
        run: mvn -B test -DskipITs=true

  e2e:
    name: E2E (opt-in)
    if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'run-e2e')
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run E2E tests (no secrets)
        working-directory: app-core
        run: mvn -B test

      - name: Upload backup artifacts (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backups
          path: app-core/data/*.bak

  e2e-with-secrets:
    name: E2E (opt-in with secrets)
    # Only run this job for manual workflow_dispatch where use_secrets == 'true'
    if: github.event_name == 'workflow_dispatch' && (github.event.inputs.use_secrets == 'true')
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run E2E tests (with secrets)
        working-directory: app-core
        env:
          UPLOAD_ENDPOINT: ${{ secrets.UPLOAD_ENDPOINT }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: mvn -B test

      - name: Upload backup artifacts (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backups
          path: app-core/data/*.bak
