name: E2E (opt-in)

# Manual / workflow_dispatch triggered E2E run for heavier integration tests
on:
  workflow_dispatch:
    inputs:
      use_secrets:
        description: 'Set to "true" to populate repository secrets into the environment for this run'
        required: false
        default: 'false'
  repository_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build and run tests
        env:
          # Only inject secrets into env when the manual input `use_secrets` is 'true'
          UPLOAD_ENDPOINT: ${{ github.event.inputs.use_secrets == 'true' && secrets.UPLOAD_ENDPOINT || '' }}
          AUTH_TOKEN: ${{ github.event.inputs.use_secrets == 'true' && secrets.AUTH_TOKEN || '' }}
        run: |
          cd app-core
          mvn -DskipTests=false test

# Notes:
# - This workflow is opt-in (manual trigger). To run E2E against a real environment that
#   talks to external services, set repository secrets and modify the steps to provide
#   necessary environment variables (e.g. UPLOAD_ENDPOINT, AUTH_TOKEN).
# - If you want scheduled nightly runs, add 'schedule' to the 'on' section.
